version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Starting prebuild phase"
  build:
    commands:
      - echo "Installing maven for code compilation, run test and package code for deployment"
      - mvn install
      - codebuild-breakpoint
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - target/messageUtil-1.0.jar 
    - echo "application artifact has been generated and posted to S3"
